"""Pre-build: extract embedded page, gzip it, generate PROGMEM header.

Reads src/index.html (the editable page source), writes src/index_html_gz.h
only when the gzipped bytes actually change, so incremental builds stay fast.

If src/index.html is missing (fresh clone, header not yet generated), the page
is extracted from the INDEX_HTML raw literal in web_config.cpp.
"""
import gzip
import os
import re
import sys

# SCons exec 上下文中 __file__ 不可用，回退到 cwd（PlatformIO 从项目根目录运行）
try:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    ROOT = os.getcwd()
if not os.path.isdir(os.path.join(ROOT, "src")):
    ROOT = os.getcwd()
SRC = os.path.join(ROOT, "src")
INDEX_HTML = os.path.join(SRC, "index.html")
WEB_CONFIG = os.path.join(SRC, "web_config.cpp")
HEADER = os.path.join(SRC, "index_html_gz.h")


def read_page():
    if os.path.exists(INDEX_HTML):
        with open(INDEX_HTML, "rb") as f:
            return f.read()
    with open(WEB_CONFIG, encoding="utf-8") as f:
        src = f.read()
    m = re.search(r'R"rawliteral\((.*?)\)rawliteral"', src, re.S)
    if not m:
        sys.exit("page: no raw literal found in web_config.cpp")
    page = m.group(1).encode("utf-8")
    with open(INDEX_HTML, "wb") as f:
        f.write(page)
    return page


def main():
    page = read_page()
    gz = gzip.compress(page, 9, mtime=0)  # mtime=0：输出确定，内容不变则不重写头文件
    lines = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i + 16]
        lines.append(", ".join("0x%02X" % b for b in chunk))
    body = "#include <pgmspace.h>\n\n" \
           "// Generated by scripts/gen_page_gz.py - DO NOT EDIT.\n" \
           "// Source: src/index.html (%d bytes -> %d gzipped, %.0f%%)\n" \
           "// aligned(4): lwIP precache 对源数据做 word 级访问，奇数基址会触发\n" \
           "// EXCCAUSE=3 LoadStoreError 崩机，必须保证数组 4 字节对齐。\n" \
           "static const uint8_t INDEX_HTML_GZ[] PROGMEM __attribute__((aligned(4))) = {\n%s\n};\n" \
           % (len(page), len(gz), 100.0 * len(gz) / len(page), ",\n".join(lines))
    old = ""
    if os.path.exists(HEADER):
        with open(HEADER, encoding="utf-8") as f:
            old = f.read()
    if old != body:
        with open(HEADER, "w", encoding="utf-8") as f:
            f.write(body)
        print("page: regenerated index_html_gz.h (%d -> %d bytes)" % (len(page), len(gz)))
    else:
        print("page: index_html_gz.h up to date (%d -> %d bytes)" % (len(page), len(gz)))


main()
